apiVersion: skaffold/v2beta11
kind: Config
build:
    local:
        push: false
    artifacts:
        - image: jopealgorta/multi-client
          context: client
          docker:
              dockerfile: Dockerfile.dev
          sync:
              manual:
                  - src: 'src/**/*.js'
                    dest: '.'
                  - src: 'src/**/*.css'
                    dest: '.'
                  - src: 'src/**/*.html'
                    dest: '.'
deploy:
    kubectl:
        manifests:
            - k8s/client-deployment.yaml
